# Change these first
owner: 0ur0b0r0s # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Elos
    url: https://elos.vc
  - name: Elos Hmg
    url: https://h.elos.dev
  - name: Mconf
    url: https://mconf.com

status-website:
  cname: upptime.mconf.dev
  logoUrl: https://mconf.com/images/logo_footer.png
  introTitle: "**Mconf Status Page**"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
