# Change these first
owner: mconf # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Elos (elos.vc)
    url: https://elos.vc
  - name: Elos API
    url: https://api.elos.vc
    expectedStatusCodes:
      - 404
  - name: Mconf
    url: https://mconf.com
  - name: Elos (Homologação)
    url: https://h.elos.dev
  - name: Elos API (Homologação)
    url: https://api.h.elos.dev
    expectedStatusCodes:
      - 404

status-website:
  cname: status.h.elos.dev
  logoUrl: https://mconf.com/images/apple-icon-57x57.png
  name: Mconf
  introTitle: "**Elos Status**"
  navbar:
    - title: Status
      href: /
    - title: Elos
      href: https://elos.vc/site/pt
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 */1 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 */1 * * *"
  uptime: "*/5 * * * *"
