# Change these first
owner: 0ur0b0r0s # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Elos (elos.vc)
    url: https://elos.vc
  - name: Elos (h.elos.dev)
    url: https://h.elos.dev
  - name: Elos (api.elos.vc)
    url: https://api.elos.vc
  - name: Mconf
    url: https://mconf.com

status-website:
  cname: upptime.mconf.dev
  logoUrl: https://mconf.com/images/apple-icon-57x57.png
  name: Mconf
  introTitle: "**Mconf Status Page**"
  navbar:
    - title: Status
      href: /
    - title: Elos
      href: https://elos.vc/site/pt
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 */1 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 */1 * * *"
  uptime: "*/5 * * * *"
